### PR TITLE
Turn relative paths in config.properties into absolute paths when running felix:config rake task

### PR DESCRIPTION
**Pull request by mbklein**

### CODE REVIEW

**Comment by cjcolvar** [comment]
Could you add some tests for JavaProperties?

**Comment by mbklein** [comment]
Yep yep!

**Comment by mbklein** [comment]
Changed my mind about this PR. Doing a little refactor first.

**Comment by mbklein** [comment]
@cjcolvar The tests are in the new dot-properties gem. :)

**Pull request merged**
